/*   */ package sun.util.resources;
/*   */ 
/*   */ public final class LocaleNames_es_US extends LocaleNamesBundle
/*   */ {
/*   */   protected final Object[][] getContents()
/*   */   {
/* 7 */     return new Object[][] { { "AN", "Antillas Neerlandesas" }, { "AX", "Islas Åland" }, { "BA", "Bosnia-Herzegovina" }, { "BH", "Bahréin" }, { "CC", "Islas Cocos (Keeling)" }, { "CX", "Isla Navidad" }, { "CZ", "República Checa" }, { "EH", "Sáhara Occidental" }, { "FK", "Islas Falkland (Malvinas)" }, { "HK", "Hong-Kong, Región administrativa especial de China" }, { "KG", "Kirguistán" }, { "KM", "Comoras" }, { "LC", "Saint Lucia" }, { "LS", "Lesotho" }, { "MO", "Macao, Región administrativa especial de China" }, { "MW", "Malawi" }, { "NL", "Países Bajos" }, { "NU", "Isla Niue" }, { "PG", "Papúa Nueva Guinea" }, { "PK", "Pakistán" }, { "PN", "Pitcairn" }, { "PS", "Territorios Palestinos" }, { "PW", "Palau" }, { "RO", "Rumanía" }, { "SA", "Arabia Saudí" }, { "SH", "Santa Elena" }, { "TF", "Territorios Australes Franceses" }, { "TK", "Islas Tokelau" }, { "TT", "Trinidad y Tabago" }, { "VI", "Islas Vírgenes de los Estados Unidos" }, { "aa", "afar" }, { "ab", "abjaso" }, { "ae", "avéstico" }, { "ak", "akan" }, { "an", "aragonés" }, { "av", "avar" }, { "ay", "aymara" }, { "az", "azerí" }, { "ba", "bashkir" }, { "bh", "bihari" }, { "bm", "bambara" }, { "bn", "bengalí" }, { "bs", "bosnio" }, { "ce", "checheno" }, { "ch", "chamorro" }, { "cr", "cree" }, { "cu", "eslavo eclesiástico" }, { "cv", "chuvash" }, { "dv", "divehi" }, { "dz", "dzongkha" }, { "ee", "ewe" }, { "eu", "vasco" }, { "ff", "fula" }, { "fj", "fidjiano" }, { "fo", "feroés" }, { "fy", "frisón" }, { "gu", "gujarati" }, { "gv", "gaélico manés" }, { "hi", "hindi" }, { "ho", "hiri motu" }, { "ht", "haitiano" }, { "hz", "herero" }, { "ie", "interlingue" }, { "ig", "igbo" }, { "ii", "sichuan yi" }, { "io", "ido" }, { "jv", "javanés" }, { "kg", "kongo" }, { "ki", "kikuyu" }, { "kj", "kuanyama" }, { "kk", "kazajo" }, { "km", "jemer" }, { "kn", "canarés" }, { "kr", "kanuri" }, { "ks", "cachemiro" }, { "ku", "kurdo" }, { "kv", "komi" }, { "kw", "córnico" }, { "ky", "kirghiz" }, { "lb", "luxemburgués" }, { "lg", "ganda" }, { "li", "limburgués" }, { "lu", "luba-katanga" }, { "mh", "marshalés" }, { "mr", "marathi" }, { "nb", "bokmal noruego" }, { "nd", "ndebele septentrional" }, { "ng", "ndonga" }, { "nn", "nynorsk noruego" }, { "nr", "ndebele meridional" }, { "nv", "navajo" }, { "ny", "nyanja" }, { "oc", "occitano (después del 1500)" }, { "oj", "ojibwa" }, { "os", "osético" }, { "pi", "pali" }, { "rm", "reto-romance" }, { "rn", "kiroundi" }, { "rw", "kinyarwanda" }, { "sc", "sardo" }, { "sd", "sindhi" }, { "se", "sami septentrional" }, { "sl", "esloveno" }, { "sn", "shona" }, { "ss", "siswati" }, { "st", "sesotho" }, { "su", "sundanés" }, { "sw", "swahili" }, { "tg", "tayiko" }, { "ti", "tigriña" }, { "tn", "setchwana" }, { "to", "tonga (Islas Tonga)" }, { "tw", "twi" }, { "ty", "tahitiano" }, { "ug", "uigur" }, { "uk", "ucraniano" }, { "uz", "uzbeko" }, { "ve", "venda" }, { "vo", "volapük" }, { "wa", "valón" }, { "za", "zhuang" } };
/*   */   }
/*   */ }

/* Location:           C:\Program Files\Java\jdk1.7.0_79\jre\lib\rt.jar
 * Qualified Name:     sun.util.resources.LocaleNames_es_US
 * JD-Core Version:    0.6.2
 */